

stages:
  - test

lint-test-job-two:
  stage: test
  tags:
    - osc
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

lint-test-job:
  stage: test
  tags:
    - osc
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
