

stages:
  - test

unit-test-job:
  stage: test 
  image:
    name: $CI_REGISTRY/dreamhost/kubectl-helm-docker
    pull_policy: always
  tags:
    - osc
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  tags:
    - osc
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
