stages:
    - publish

variables:
    TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID
    LATEST_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    DOCKER_API_VERSION: "1.39"

publish:
    stage: publish
    tags:
    - OSC
    image: docker:stable-dind
    script:
        - docker build -t $TAG -t $LATEST_TAG .
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $TAG
        - docker push $LATEST_TAG
