stages:
    - test
    - publish

variables:
    TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID
    LATEST_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    DOCKER_API_VERSION: "1.39"

test:
    stage: test
    tags:
    - loyalty
    image: mcr.microsoft.com/dotnet/sdk:5.0
    script: 
        - "dotnet test Pushka.Application.Tests/Pushka.Application.Tests.csproj"

publish:
    stage: publish
    tags:
    - loyalty
    image: docker:stable-dind
    script:
        - docker build -t $TAG -t $LATEST_TAG .
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $TAG
        - docker push $LATEST_TAG
